name: Linting des fiches

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
  lint:
    name: "Linting with markdownlint"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: npm run lint
